Repository final-project-onlineshop/teknoza, pull requests merged in 2022-09, with the labels that each got.

#114 Omer create order list screen
  frontend/src/App.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/pages/ordersPage/OrdersPage.tsx
  frontend/src/pages/ordersPage/ordersPage.scss
Labels: enhancement

#117 omer : users page created
  frontend/src/App.tsx
  frontend/src/pages/usersPage/UsersPage.tsx
  frontend/src/pages/usersPage/usersPage.scss
Labels: enhancement

#127 bkr-create-datajs : updated data.js with our basic database..
  backend/data.js
Labels: enhancement

#128 bkr-test-auths : auths tested..
  backend/config.js
  backend/index.js
  backend/models/userModel.js
  backend/test.rest
Labels: bug, enhancement

#132 bkr-create-gmail: gmail account created and added to .env..
  backend/utils.js
Labels: enhancement

#136 Omer update browser title with inhalt
  .gitignore
  .vscode/settings.json
  frontend/src/components/header/Header.tsx
  frontend/src/pages/cartPage/CartPage.tsx
  frontend/src/pages/dashboardPage/DashboardPage.tsx
  frontend/src/pages/homePage/HomePage.tsx
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/orderHistoryPage/OrderHistoryPage.tsx
  frontend/src/pages/ordersPage/OrdersPage.tsx
  frontend/src/pages/paymentPage/PaymentPage.tsx
  frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx
  frontend/src/pages/productEditPage/ProductEditPage.tsx
  frontend/src/pages/productPage/ProductPage.tsx
  frontend/src/pages/productsPage/ProductsPage.tsx
  frontend/src/pages/registerPage/RegisterPage.tsx
  frontend/src/pages/shippingPage/ShippingPage.tsx
  frontend/src/pages/usersPage/UsersPage.tsx
Labels: enhancement

#137 bkr-create-order-router : order router created..
  backend/index.js
  backend/routes/orderRoutes.js
  backend/test.rest
Labels: enhancement

#140 omer : order details page created
  frontend/src/App.tsx
  frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx
  frontend/src/pages/orderDetailsPage/orderDetailsPage.scss
Labels: enhancement

#149 sevde: created-user-edit-page, closed #91
  .vscode/settings.json
  frontend/src/pages/userEditPage/UserEditPage.tsx
  frontend/src/pages/userEditPage/userEditPage.scss
Labels: enhancement

#146 bkr-add-new-testing : new route testing added to test.rest..
  backend/routes/userRoutes.js
  backend/test.rest
  frontend/package-lock.json
Labels: bug, enhancement

#151 bkr-fix-ug-in-post-product : bug fixed and tested..
  backend/routes/productRoutes.js
  backend/routes/userRoutes.js
  backend/test.rest
Labels: bug

#153 bkr-fix-search-product-bug : search path is ready..
  backend/routes/productRoutes.js
  backend/test.rest
Labels: bug

#156 Omer import dummy database into mongo
  .vscode/settings.json
  backend/data.js
  backend/models/productModel.js
Labels: enhancement

#158 bkr-test-githash : testing git stash
  backend/test.rest
Labels: documentation

#165 bkr-check-product-routes : updated.. und bug fixed.. have to be tested..
  backend/index.js
  backend/routes/productRoutes.js
Labels: bug

#167 Omer fix be connections for new update
  frontend/src/components/product/Product.tsx
  frontend/src/components/rating/Rating.tsx
  frontend/src/pages/productPage/ProductPage.tsx
Labels: enhancement

#168 Omer create order summary component
  frontend/src/components/orderSummary/OrderSummary.tsx
  frontend/src/components/orderSummary/orderSummary.scss
  frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx
  frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx
Labels: enhancement

#169 sevde: added useFormik for validations before backend, closed #121
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/loginPage/loginPage.scss
  frontend/src/pages/registerPage/RegisterPage.tsx
  frontend/src/pages/registerPage/registerPage.scss
Labels: enhancement

#170 Omer create private routing
  frontend/src/App.tsx
  frontend/src/Store.tsx
  frontend/src/components/adminRoute/AdminRoute.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/components/protectedRoute/ProtectedRoute.tsx
  frontend/src/pages/loginPage/LoginPage.tsx
  frontend/src/pages/registerPage/RegisterPage.tsx
Labels: enhancement

#171 sevde: added photo-album in product datails page
  frontend/src/pages/productPage/ProductPage.tsx
  frontend/src/pages/productPage/productPage.scss
Labels: enhancement

#173 bkr-fix-sarch-bug : fixed bug.. can be tested with test.rest..
  backend/routes/productRoutes.js
  backend/test.rest
Labels: bug

#178 bkr-fix-product-post-put : fixed. but can not be tested.
  backend/models/productModel.js
  backend/routes/productRoutes.js
  backend/routes/userRoutes.js
  backend/test.rest
Labels: bug
