Repository final-project-onlineshop/teknoza, pull requests merged in 2022-10, with the labels that each got.

#185 bkr-add-hetzner-testing : updated test for hetzner backend route..
  backend/requests.http
Labels: enhancement

#186 bkr-update-datajs : datajs updated..
  backend/data.js
Labels: enhancement

#189 bkr-update-database : database updated..
  backend/index.js
Labels: enhancement

#193 bkr-create-dummy-datajs : created.
  backend/.gitignore
  backend/data.js
  backend/dummy_data.js
  backend/index.js
  backend/routes/seedRoutes.js
Labels: enhancement

#194 Omer update cart page for dynamic content
  frontend/src/App.tsx
  frontend/src/Store.tsx
  frontend/src/components/orderSummary/OrderSummary.tsx
  frontend/src/components/productInCart/ProductInCart.tsx
  frontend/src/components/productInCart/productInCart.scss
  frontend/src/pages/cartPage/CartPage.tsx
  frontend/src/pages/productPage/ProductPage.tsx
  frontend/src/pages/searchPage/SearchPage.tsx
Labels: enhancement

#210 omer : ptc button fixed
  frontend/src/pages/cartPage/CartPage.tsx
Labels: bug

#209 omer : fixed badge count in cart
  frontend/src/components/header/Header.tsx
Labels: bug

#214 Omer update shipping page as dynamically
  frontend/src/Store.tsx
  frontend/src/pages/shippingPage/ShippingPage.tsx
Labels: enhancement

#217 omer : add to cart button component created
  frontend/src/Store.tsx
  frontend/src/components/addToCartButton/AddToCartButton.tsx
  frontend/src/components/addToCartButton/addToCartButton.scss
  frontend/src/components/product/Product.tsx
  frontend/src/components/product/product.scss
  frontend/src/components/productInCart/ProductInCart.tsx
  frontend/src/pages/productPage/ProductPage.tsx
  frontend/src/pages/searchPage/SearchPage.tsx
Labels: bug

#221 bkr-add-average-rating : average rating added to database..
  backend/data.js
  backend/models/productModel.js
  backend/routes/seedRoutes.js
Labels: bug, enhancement

#223 bkr-fix-bug-in-product-search : bug fixed. but must be checked with frontend..
  backend/routes/productRoutes.js
  backend/test.rest
Labels: bug

#225 bkr-fx-bug-in-reviews : bug fixed..
  backend/routes/productRoutes.js
Labels: bug

#227 bkr-add-test-rest : added test.rest without token and users..
  backend/.gitignore
  backend/test.rest
Labels: enhancement

#229 bkr-fix-bug-bearer : fixed
  backend/utils.js
Labels: bug

#232 fix account link in user menu, #closes 200
  frontend/src/App.tsx
  frontend/src/components/header/Header.tsx
  frontend/src/pages/profilePage/ProfilePage.tsx
Labels: dependencies

#235 bkr-fix-bug-in-profile : /profile user update fixed..
  backend/routes/userRoutes.js
Labels: bug

#237 bkr-fix-paypal-client : bug fixed..
  backend/config.js
Labels: bug

#239 omer : prices updated after testing
  frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx
Labels: enhancement

#244 Omer update orders page for admins dynamically
  frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx
  frontend/src/pages/orderHistoryPage/OrderHistoryPage.tsx
  frontend/src/pages/ordersPage/OrdersPage.tsx
  frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx
  frontend/src/utils.js
Labels: enhancement

#248 omer : admin products page updated
  backend/routes/productRoutes.js
  frontend/src/pages/orderDetailsPage/OrderDetailsPage.tsx
  frontend/src/pages/productsPage/ProductsPage.tsx
Labels: enhancement

#253 sevde: fixed item filtering sub navbar-without sales, closes #197
  frontend/package-lock.json
  frontend/src/components/header/Header.tsx
Labels: dependencies

#254 Omer update admin edit product page dynamically
  frontend/src/pages/placeOrderPage/PlaceOrderPage.tsx
  frontend/src/pages/productEditPage/ProductEditPage.tsx
  frontend/src/pages/profilePage/ProfilePage.tsx
Labels: enhancement

#257 sevde: added reviews in product details page, closes #252
  frontend/src/pages/productPage/ProductPage.tsx
Labels: dependencies

#260 bkr-fix-bug-in-nodemailer : bug fixed..
  backend/routes/orderRoutes.js
  backend/routes/productRoutes.js
  backend/test.rest
  backend/utils.js
Labels: bug

#265 sevde: updated admin dashboard page, closes #263
  frontend/src/pages/dashboardPage/DashboardPage.tsx
  frontend/src/pages/productPage/ProductPage.tsx
Labels: enhancement

#267 omer: toasting fixed
  frontend/src/App.tsx
Labels: bug
